### ISSUE TITLE
can't open GDB ImageWatch window in Qt Creator

### ISSUE THREAD

**Issue by howard-mahe** [csantosbh/gdb-imagewatch#18]
Hi,

The GDB ImageWatch window doesn't open when I hit a breakpoint and typing the command `plot variable_name` in the Qt Creator's Debugger Log doesn't work either (Undefined command 'plot').

My config is the following:
- Ubuntu 14.04
- Python 3.4.3
- gdb 7.10
- CMake 3.9.3
- Qt 5.9.1
- Qt Creator 4.4.0

My Qt Creator options:
- I set the _Debugger_ path to gdb 7.10 and the _CMake_ path to the CMake 3.9.3
- I also add `/usr/local/bin/gdb-imagewatch/gdb-imagewatch.py` in _Extra Debugging Helpers_.

I test the installation with `python3 /path/to/gdb-imagewatch/gdb-imagewatch.py --test`, it works fine.

Any idea to make it works?

**Comment by csantosbh** [comment]
Hi Howard, thanks for the detailed report!

It appears that, since version 1.1, the plugin is no longer being correctly loaded via the QtCreator *Extra Debugging Helpers* menu. I will fix that in the next version.

In the meantime, as a workaround, I suggest loading the plugin by inserting `source /path/to/gdb-imagewatch/gdb-imagewatch.py` into your `~/.gdbinit` file. The QtCreator integration should still work, the only difference is that the plugin will be loaded by GDB instead of QtCreator itself.
