### ISSUE TITLE
giwtype.py for Eigen::Matrix or Eigen::Map

### ISSUE THREAD

**Issue by JensAc** [csantosbh/gdb-imagewatch#23]
Thanks for the great work!
I wrote giwtype.py for types of the Eigen library. I could share it via a gist. Another possibility would be to modify your file and put if-else statements in there and file a pull request. However, I think that is not optimal. What do you think about an abstract class implementing the functions needed and loading automatically the applicable for the type to be displayed? This way it would be really easy to contribute to the repo, as only derived classes need to be implemented. 
Maybe I can also take a look into that, when I have time.

**Comment by csantosbh** [comment]
Awesome! Thanks for contributing :)

I like your second idea too. I could define a simple interface that all types should implement. Secondly, we could have a "giwtype" directory instead of a "giwtype.py" script. For every supported format, we could have a separate python script inside the giwtype folder dealing with that particular format (e.g. cvmat.py, eigenmat.py, stdvector etc). Then, the plugin could automatically load all scripts within that folder and support all available formats simultaneously.

Optionally, the user could disable arbitrary formats by making changes to the config.ini file.

What do you think?

**Comment by JensAc** [comment]
A giwtype directory with different scripts for every type would be perfect. Supporting all the types simultaneously is also a really good idea as you may have different kinds of buffers needed for different tasks. Configuration via config.ini would be really fine.

**Comment by csantosbh** [comment]
Great. I'm adding this to the next major milestone.

**Comment by csantosbh** [comment]
The initial implementation is up! It can be accessed in the branch v1.2-dev.

Now the user only needs to create a new file under giwscripts/giwtypes and derive the class `giwscripts.giwtypes.interface.TypeInspectorInterface`.
I tried as much as possible to keep the previous interface (that is, method names and their parameters). The only difference is the wrapping class and the first `self` parameter. The plugin should automatically load all implementations at runtime.

Feel free to submit the implementation for the Eigen buffers.

Thanks again!

**Comment by JensAc** [comment]
Actually, we need some more modifications as Eigen stores Matrices by default in ColMajor. Therefore we need the opportunity to define a colstride as well. I'll take a look into that and file a pull request, when everything works fine.

**Comment by csantosbh** [comment]
Actually, a colstride field would only be useful for skipping channels inside an image (like only shoing the R channel in an RGB image). In the case of colmajor buffers, we need support to render transposed buffers.

To achieve that we need a new `transpose` flag in the metadata API. The transposition itself might be doable by accounting for this transform in the object pose matrix. I'll check the viability of this (it's important to make sure that the value renderer doesn't break) and will update the discussion with possible solutions for this.

**Comment by csantosbh** [comment]
Initial support for transposed buffers is finally finished! Currently, the following buffers are plotting fine:

```cpp
    Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor> teste0(3, 4);
    Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> teste1(3, 4);
    Eigen::Vector3f teste2;
    Eigen::Matrix2f teste3;
    Eigen::VectorXf teste4(5);
    teste0 << 8, 2, 2, 9,
            9, 1, 4, 4,
            3, 5, 4, 5;
    teste1 << 8, 2, 2, 9,
            9, 1, 4, 4,
            3, 5, 4, 5;
    teste2 << 4, 5, 6;
    teste3 << 0, 1, 2, 3;
    teste4 << 0, 1, 2, 3, 4;

    Eigen::Map<Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor>> teste5(teste0.data(), 3, 4);
    Eigen::Map<Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>> teste6(teste1.data(), 3, 4);
    Eigen::Map<Eigen::Vector3f> teste7(teste2.data());
    Eigen::Map<Eigen::Matrix2f> teste8(teste3.data());
    Eigen::Map<Eigen::VectorXf> teste9(teste4.data(), 5);
```

I had to perform some modifications in the eigen3 giwtype script, so please feel free to suggest improvements.

There are a few things that can be improved here:
 * ~~Rotation is inverted for colmajor buffers. This is a big issue and shall be fixed in the near future~~
 * ~~Buffer size in the icon list is swapped for transposed buffers. I'll look into that when I'm certain everything is stable.~~

The following will be left for the future should the need for them arise:
 * Support for Eigen::Map row (outer) strides. This is somewhat of a low priority, but can be done somewhat easily.
 * Support for Eigen::Map col (inner) strides. Very low priority at the moment. Would require some big changes in the rendering engine.

**Comment by csantosbh** [comment]
The feature seems to be stable now. The only thing that remains to be done now is to update the documentation on how to handle custom buffers.

Thank you for providing support on this task!

**Comment by JensAc** [comment]
I tested the feature for my test cases and it seems to work fine! Thank you very much! 
I am fine with all your modifications on eigen3 giwtype script. 
If I find other use cases for your tool, I will file pull requests. 
I'm closing this now...solved!
