### ISSUE TITLE
change request: glTexStorage2D to glTexImage2D

### ISSUE THREAD

**Issue by djdane** [csantosbh/gdb-imagewatch#35]
Hi, great tool you made!
However, I would like to use it with my default Qt 5.5.1 I got from 16.04. - you require Qt 5.6.
To run on Qt 5.5.1 I had to change from QOpenGLFunctions to QOpenGLExtraFunctions in gl_canvas.h.
As far as I noticed, the only difference is glTexStorage2D method which is not supported.
I followed suggestions in https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexStorage2D.xhtml to change it to glTexImage2D, e.g. in buffer.cpp:
`//            gl_canvas_->glTexStorage2D(
//                GL_TEXTURE_2D, 1, GL_RGBA32F, buff_w, buff_h);
            gl_canvas_->glTexImage2D(GL_TEXTURE_2D, 1, GL_RGBA32F,
                        buff_w, buff_h, 0, tex_format, tex_type, NULL);`

However, I get the black images when I run the: python3 gdb-imagewatch.py --test
So, can you make it work with glTexImage2D and Qt 5.5? Thanks a lot!

**Comment by csantosbh** [comment]
Hello, thanks for taking the time to try to fix this! Could you tell me if there are any error messages in the console when you invoke the `python3 gdb-imagewatch.py --test` command?

By the way, if you installed Qt manually, you can use the `MaintenanceTool` binary (located under the installation root) to install multiple versions of the Qt libraries simultaneously, without them conflicting with each other.

**Comment by djdane** [comment]
Hi, no error messages, just black images. While hovering I see the values are changing...
Thanks for the Qt hint, I wanted to show to the colleagues your tool but we are somewhat bundled with Qt that comes with 16.04. And I really like the look&feel, very similar to VS plugin!

**Comment by csantosbh** [comment]
I see! I'll try to compile the project against Qt 5.5 to reproduce this issue and will let you know when I have more information on this issue. Thanks!

**Comment by csantosbh** [comment]
I've just managed to run imagewatch on my 16.04 machine, compiling against Qt 5.5.1 as well as 5.10.0, and with a few modifications in the code. It appears that the major difference from your modification was the second parameter of glTexImage2D, which should be 0 instead of 1.

@djdane I have pushed the candidate fix into branch `development` (10933dc), could you take a look?

**Comment by djdane** [comment]
Hi, thanks for the update, I am not able to access my 16.04 development in the next couple of days.

I tried however home on the windows machine, with cygwin was a huge failure BUT qt actually offers MinGW 5.3.0 https://www.ics.com/blog/getting-started-qt-and-qt-creator-windows, so I decided to go with it and use .pro file you supplied. Since there is no pkgconfig for python3, in your .pro file there are some modifications. I am no expert in qt but it should be possible to cross-compile, for me it compiled with:
```
#PKGCONFIG += python3
QMAKE_CXXFLAGS += -D_hypot=hypot
PY_PATH = "C:/Python"
INCLUDEPATH += $$PY_PATH/include
LIBS += -L$$PY_PATH/libs -lpython36 

```
I didn't resolved linking, though - you added src/thirdparty/Khronos, presumably for the extensions. Since you use QOpenGL already, you could use their functions for extensions directly: http://www.kdab.com/opengl-in-qt-5-1-part-1/ - I didnt finish it, should not be difficult. 
That would be nice feature to have (getting rid of /thirdparty/Khronos), since I get "unresolved reference" that are missing probably because of  MinGW (in 16.04 were no problems).

Out of topic, do you really need the whole Eigen? (btw. excellent idea for plugin with their matrix!) I just saw you are using it basically for rotation in lin_algebra.cpp - a tiny refactoring may be required though ;)

Sorry for throwing so many things at you - I am quite enthusiastic about your qt plugin.

**Comment by csantosbh** [comment]
Hello djdane! I'm quite happy to see your enthusiasm. Let's talk about your topics point by point:

**Windows support**: This has been on my radar for a long time now, but sadly it may not be as simple as compiling the plugin on Windows. The first step was taken on version 1.2, with the removal of most external dependencies. Since then, I didn't have much time to proceed with the windows port, but one issue I expect to encounter is coordinating with the signals sent to GDB (for more details, you can see [this question](https://stackoverflow.com/questions/33482870/gdb-hangs-when-multi-threaded-python-extension-is-used-to-debug-multi-threaded-p) where I talk about some issues I had when developing the plugin on Linux).

Another issue that may arise is making sure that the user has a GDB compiled against the same version of the python library that he is linking against (for instance, in your case you are linking the imagewatch plugin against python3.6, so your gdb should also have been linked against python3.6).

**Khronos headers**: One of the dependencies I had prior to v1.2 was GLEW, which did the dirty work of loading all opengl extension function pointers for me. When I started removing the external dependencies, I realized this job could be done by Qt, so I replaced GLEW by QOpenGLExtraFunctions. If I recall correctly, there were a few compilation issues related to preprocessor directives that were not defined on Qt, so I had to resort to bringing the official opengl headers from Khronos into the repo.

Since I don't recall the exact context of when I originally brought these headers in, I just tried to remove all inclusions of GL/gl.h from the development branch and it seemed to compile without any issues. I still need to test the compilation on a fresh Ubuntu install to make sure this is correct, but if it is, I will be removing the Khronos headers in the development branch.

**Eigen**: At the moment it is used for affine transformations (translation, scale, rotation) and matrix inversion on linear_algebra.cpp. The idea was to wrap the Eigen library under this file so that the rest of the code didn't get "contaminated" by Eigen references (which makes it easy to switch libraries in the future, if necessary). I decided not to remove this dependency because Eigen is a very optimized header only library with a greatly convenient API.

Thanks for taking the time for providing your valuable insights!

**Comment by djdane** [comment]
Hi! Sorry for being away so long. 
I tested development version and it all went well, however, there is still black screen :( 
On the positive side, when I right-click and "export buffer" the image is saved and visible!
Again, everything is without warnings/errors being displayed.

Thanks for sharing the history of the project, now some more thoughts.
Windows support: I get the point about signals on windows + python issue, though I still hope successful porting is possible.  Cannot say more on that, except that Qt guys did a good job on that, which brings me to the next points.
QOpenGLFunctions: I see that now you mix Khronos and QOpenGLFunctions, of course it is fun but I think that it may be cleaner without Khronos dependencies and sticking to QOpenGLFunctions way. Again, I am by no means expert to give advice, however, please see this simple example http://doc.qt.io/qt-5/qtopengl-cube-example.html. There are many similarities with your project that you can directly incorporate for a cleaner implementation; like mainwidget.h deriving (not publicly!) from QOpenGLFunctions, the usage of QOpenGLBuffer in geometryengine.h and also a hint to pimp your .pro (check version of Qt, PKGCONFIG may not be supported, etc.). And lastly, Eigen: Yes it is a great library but I was thinking about functionalities from http://doc.qt.io/qt-5/qmatrix4x4.html, there are exact functions you need (e.g. rotate, inv) and you don't need another library since you are already using Qt (performance should not be the issue).

Now I already sound to myself overly Qt-ish, and it was clearly not your intention to use GDB imagewatch only on Qt (than it would be Qt imagewatch ;) ).  
Thanks again and keep up the great work!

**Comment by brunoalr** [comment]
Hi @djdane!

First the good news: I was able to have OID (the new name of GIW) on Windows! The only catch is that I only tested compiling it with some specific compiler which I don't recall now, probably TDM-GCC because... reasons :P So I consider Windows support as experimental for now. Ideally I want to give support to MSVC.

If you are still enthusiastic about the project you could help us a lot with a Pull Request regarding QOpenGLFunctions :) I do not know if you saw it, but we moved development to https://github.com/OpenImageDebugger/OpenImageDebugger/. Feel free to keep sending us suggestions there, as we will archive this repo soon. - it will become read-only
