### ISSUE TITLE
crash of gdb-imagewatch.py --test

### ISSUE THREAD

**Issue by nolyn** [csantosbh/gdb-imagewatch#40]
Hi,
I'm trying to get gdb image watch to work on my system. I build it according to the Readme. I assume this means that my system meets the listed requirements. I'm using an up-to-date arch linux installation. Notably my Qt version is 5.11 and my gdb version is 8.1. Can those be too high?

Running 
```
gdb-imagewatch.py --test
```
results in a segmentation fault. I tried to track the problem by running the command in PyCharm in debugging mode. The last line that is reached is 101 in giwwindow.py:
```
            self._bridge.queue_request(plot_callable)
```
Further a get a warning when I run the command:
```
WARNING: QApplication was not created in the main() thread.
```
Any idea what the problem might be? Let me know if I can provide further information.

**Comment by csantosbh** [comment]
Hello @nolyn, thank you for reporting this issue!

In principle, I believe that your GDB version should not be behind this strange behavior, since GDB is not involved in the process of testing the plugin when it is called with from the command line via `gdb-imagewatch.py --test`. So the possibilities were left to the Qt and Python versions.

I upgraded to both Qt 5.11.0 and Qt 5.11.1, while using python 3.5.2, but was unable to reproduce the issue. Perhaps this could be related to your python installation. Could you tell me which python version you have installed on your machine?

Another, less likely possibility, is that you could have multiple versions of Qt on your machine, but compiled the plugin using the wrong one. Might be worth checking it out by recompiling with `make clean; make V=1` and checking the directory for your qt toolchain (when using Qt 5.11.1, mine is `/opt/Qt/5.11.1/gcc_64/bin/`, for instance).

**Comment by nolyn** [comment]
Hi @csantosbh, thanks a lot! The problem was the python version. I have python 3.6.5 installed. I installed 3.5.5 too, if I call it with that it works. 
Great tool, I've been using it already for a while, just not on my Laptop yet. Now I can use it there too. Thanks!

**Comment by csantosbh** [comment]
Glad to hear it's working! The fact that the plugin is incompatible with Python 3.6.5 really worries me, so I'll try to find a solution for that, thanks for testing it.
