### ISSUE TITLE
How to debug gdb-imagewatch

### ISSUE THREAD

**Issue by nolyn** [csantosbh/gdb-imagewatch#41]
Hi @csantosbh,
I want to add some types. I read the blog post, but before I dig deeper I was wandering if you have any advice on how to debug the gdb-imagewatch. I have lots of types, which are not observed directly, but as members of classes. Additionally an instance of a classe can have several variables which should be observable. Looking at the functions get_available_symbols and get_fields_from_type I think gdb-imagewatch might already be capable of finding those variables. 
How can I investigate what gdb-imagewatch is observing at run-time? Do I have to start my c++ application in debug mode, wait until the imagewatch opens and attach to the process? I think this will already be too late, but I didn't try it yet.

**Comment by brunoalr** [comment]
@nolyn you can do that by running two instances of gdb:

In the first one you run your application, no need to attach to a running process (make sure you have compiled gdb-imagewatch in DEBUG mode, though).

In the second one you **must NOT** call `source gdb-imagewatch.py` (check you `~/.gdbinit` config file) and should attach to the first running gdb instance.

Then you just call `run` in the first instance.

@csantosbh please confirm if these instructions are correct.

**Comment by nolyn** [comment]
thanks for sharing this. i'll try it out, once I get some time and report back

**Comment by csantosbh** [comment]
@brunoalr thank you dearly for addressing the issue! Sadly I've been quite absent in the past few months due to personal issues, but things are starting to go back to normal.

Your comments are correct when it comes to debugging changes to the native part of GDB ImageWatch itself. However, when creating new giwtypes (which is what I believe is the original concern expressed by @nolyn ), there was no official tool to, say, print all the symbols that were analyzed by the plugin.

Therefore I created some decorators that can make this task a bit easier. There are now two decorators:
`@interface.debug_buffer_metadata` and `@interface.debug_symbol_observable` that can be placed prior to the methods `get_buffer_metadata` and `is_symbol_observable`, respectively. They can be appended to the methods of any giwtype class, and will display information about each symbol that was processed by the tool, revealing whether or not a symbol was considered observable and if it raised an exception while being parsed.

**Comment by nolyn** [comment]
Thanks, I think this will be very helpful. 

I have typically some objects with have several images as members. I added some giwtypes to display one of them. Displaying all of them is not possible I believe, since the backend only checks if the parent was already processed, which is the case after the first member was found. I thought about changing the backend such, that all variables are parsed down to all members and then only add giwtypes for the basic types. But I think that would require substantial changes, probably treeview instead of list and some mechanism would be required to avoid endless loops if a variable has a pointer to itself or its parent. At that time I had no idea how to debug it and created this issue. At the moment I have no time xD. I hope I will have some time in the future to look into it.

**Comment by brunoalr** [comment]
Oof, I'm some 3 years late to this party, but I will close this issue as the question was solved and create a new one for the treelist view in https://github.com/OpenImageDebugger/OpenImageDebugger/

Thanks for the suggestion, @nolyn
