### ISSUE TITLE
Fix compatibility with python 3.6.5

### ISSUE THREAD

**Issue by brunoalr** [csantosbh/gdb-imagewatch#43]
See this [discussion](https://github.com/csantosbh/gdb-imagewatch/issues/40#issuecomment-402141651)

**Comment by csantosbh** [comment]
Thanks for creating a separate ticket for this issue!

I've narrowed down the problem to the call `PyDict_GetItemString` at giw_window.cpp:231 when the item `transpose_buffer` is not present in the dictionary, which is the case in the test buffers.

The documentation for Dicts of the python3 C API (https://docs.python.org/3/c-api/dict.html) states that:

> PyDict_GetItem Return the object from dictionary p which has a key key. Return NULL if the key key is not present, but without setting an exception.

Also, for `PyDict_GetItemString`:
> This is the same as PyDict_GetItem(), but key is specified as a const char*, rather than a PyObject*.

So there seems to be a bug in the implementation of `PyDict_GetItem` for python 3.6.5. There are two workarounds for this:

1. Change the all giwtypes to always return the `transpose_buffer` field and make it obligatory
2. Use `PyDict_Contains` to check for the presence of dictionary fields before obtaining them

I'm inclined to go for solution 1, since it is simpler, while `PyDict_Contains` would require creating a PyObject from a string for each key to be tested, and the python C API is very not very clear about when `Py_decref` should be used.
