### ISSUE TITLE
usage on macbook

### ISSUE THREAD

**Issue by CanCanZeng** [csantosbh/gdb-imagewatch#45]
Hi, thank you for your great work. It's a very good tool for cv developers. I always recommend this tool to my friends.

I have a problem these days, I need to program on macbook, but there are not any tool like this to debug opencv, it's very

**Comment by CanCanZeng** [comment]
it's very annoyed to save images to visualize the intermediate variables. But I find that GDB is still working on mac. So, is there any way to use this tool on mac?

**Comment by csantosbh** [comment]
Hello @CanCanZeng! Sadly I don't own a mac to test this, but I suspect that it should be possible, since you said gdb works on mac, and I know Qt is supposed to be cross platform.

Have you tried to compile the tool on mac? I suppose the compilation steps wouldn't be very different. If you have compilation issues, I might be able to give a hint or two on how to solve them, but I can't guarantee since I don't have the means to test it (and sadly I don't know anyone who owns a mac to test it myself).

**Comment by CanCanZeng** [comment]
Thank you for your kind reply, I am new to mac, but I'm try to figure it out. I have successfully installed gdb and qtcreator on mac, but haven't yet compiled gdb-imagewatch on it. I will try it later, and I will inform you if any progress is made.

**Comment by CanCanZeng** [comment]
hi, I tried to compile gdb-imagewatch on macbook today. After fix some compilation error, I finally installed it. But there are still some error when using it.

1. when I source gdb-imagewatch.py, it outputs:
```
-bash: 
GDB-ImageWatch entry point. Can be called with --test for opening the watcher
window with a couple of sample buffers; otherwise, should be invoked by the
debugger (GDB).
: command not found
-bash: import: command not found
-bash: import: command not found
-bash: import: command not found
-bash: /usr/local/bin/gdb-imagewatch/gdb-imagewatch.py: line 16: syntax error near unexpected token `('
-bash: /usr/local/bin/gdb-imagewatch/gdb-imagewatch.py: line 16: `def get_debugger_bridge():'

```

2. when I run : _python3 /usr/local/bin/gdb-imagewatch/gdb-imagewatch.py --test_
the output error is:
```
Traceback (most recent call last):
  File "/usr/local/bin/gdb-imagewatch/gdb-imagewatch.py", line 66, in <module>
    main()
  File "/usr/local/bin/gdb-imagewatch/gdb-imagewatch.py", line 55, in main
    test.giwtest(script_path)
  File "/usr/local/bin/gdb-imagewatch/giwscripts/test.py", line 25, in giwtest
    window = giwwindow.GdbImageWatchWindow(script_path, dummy_debugger)
  File "/usr/local/bin/gdb-imagewatch/giwscripts/giwwindow.py", line 35, in __init__
    script_path + '/libgiwwindow.so')
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/bin/gdb-imagewatch/libgiwwindow.so, 6): image not found

```

3. It's more weird when I just run: _python3 /usr/local/bin/gdb-imagewatch/gdb-imagewatch.py_
it outputs
```
Traceback (most recent call last):
  File "/usr/local/bin/gdb-imagewatch/gdb-imagewatch.py", line 66, in <module>
    main()
  File "/usr/local/bin/gdb-imagewatch/gdb-imagewatch.py", line 58, in main
    debugger = get_debugger_bridge()
  File "/usr/local/bin/gdb-imagewatch/gdb-imagewatch.py", line 21, in get_debugger_bridge
    from giwscripts.debuggers import gdbbridge
  File "/usr/local/bin/gdb-imagewatch/giwscripts/debuggers/gdbbridge.py", line 7, in <module>
    import gdb
ModuleNotFoundError: No module named 'gdb'
```

Do you know what's wrong? 

The GDB is OK, I have used it to debug a c++ program.
```
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by csantosbh** [comment]
Hi @CanCanZeng! Sorry for taking so long to reply.

I've fixed the compilation issues, however, unfortunately, the architecture adopted for GDB ImageWatch means that UI calls are attempted at a secondary thread, which is not supported on MacOS (and is prone to bugs on Linux). We should probably refactor the code, having two separate processes (one for GDB and another for the UI), using IPC between them.

If you are using an older version of Mac OS than Mojave, then you might be able to run the plugin (I was only able to test on Mojave, which enforces the main thread UI restriction and prevents the plugin from running). Check out the branch `darwin-support`.

In the following weeks I'll try to make the necessary changes to use multiple processes, which would potentially make the plugin cross platform.

**Comment by CanCanZeng** [comment]
Thank you for your help, the reply is worth waiting! My Mac OS is also Mojave unfortunately. I will try the darwin-support later, although I don't understand what you are saying (ಡωಡ)

**Comment by csantosbh** [comment]
I have some good news on this. I've been working on the mac port for the past few weeks and have been able to make everything work on my MacOS Mojave. Since I couldn't get GDB to run properly here (especially when building with python 3 support), I made two major changes:

- Split the UI and debugger into two different processes
- Added support for python 2
- Added support for lldb

These changes are all in the wip/darwin-support branch. As the name suggests, this branch is still a work in progress and might be unstable, but is finally usable. I'm open to receiving some feedback from mac users.

To use it with lldb, you need to add the following to ~/.lldbinit:
```
command script import /path/to/gdb-imagewatch/giwwindow.app/Contents/MacOS/gdb_imagewatch.py
```

**Comment by brunoalr** [comment]
@csantosbh I saw you removed the dependency on pysigset... would that be enough for giw to work on Windows now too?

**Comment by csantosbh** [comment]
Almost there! There's a few places where we have platform specific python code (but these are few and probably easy to implement now since I check for OS version on them). But before that, it would be nice to make sure GDB is still working on Linux in the darwin branch (which I don't know yet as I don't have an easy linux machine at my disposal nowadays)

**Comment by brunoalr** [comment]
the installation process is broken in Linux, currently have to copy the contents of resources to the installation destination.

**Comment by brunoalr** [comment]
Solved an implemented in https://github.com/OpenImageDebugger/OpenImageDebugger/ :D
