### ISSUE TITLE
step must be divided by 8 for doubles

### ISSUE THREAD

**Issue by kameamea** [csantosbh/gdb-imagewatch#5]
With doubles I get wrong numbers for the values of the cells (at high zoom level for example), that is, every second cell is skipped. If I change gdbiwtype.py to

 elif type == GIW_TYPES_FLOAT64:
        step = int(step / 8)

I get the correct values. However as I'm not sure about other side effects of this change, I just report this here.

**Comment by csantosbh** [comment]
Thanks for the report! I originally didn't notice this because I was testing with the python buffers, whose steps are not computed by this function.

The most recent revision from the master branch contains the fix for this and a few other issues. Could you test it on your machine?

**Comment by kameamea** [comment]
doubles work perfectly now. However I see a problem now, which I at least had not realized before.
If the content of a mat changes, this is not (always?) reflected in gdb-imagewatch. Even if I click on the thumbnail of the mat I still get the old content (and size). Only by typing the name of the mat again in the "add symbols"-text field I'm able to visualize the new content. This is sub-optimal.

**Comment by csantosbh** [comment]
I agree, this is a terrible behavior and must be fixed. I saw that happening shortly after the new feature of automatically re-loading buffers from the previous debug session was introduced (1a2247a1c56f7413a8c75e76a03d54fac1e78ef7), but I thought it was completely fixed by e271ad0c13ce8b5261f93605215720d1a4132366.

Could you provide a simple code test case where that behavior can be reproduced?

**Comment by kameamea** [comment]
Looks like I was not using the latest branch, so far with the fix it looks good.
